import { isValidCardNumber } from '../js/luhn';

describe('isValidCardNumber', () => {
  // Test numbers of the kind generated by https://www.freeformatter.com/credit-card-number-generator-validator.html
  test.each([
    ['4111111111111111', 'Visa'],
    ['5555555555554444', 'MasterCard'],
    ['2223000048400011', 'MasterCard (2-series)'],
    ['378282246310005', 'American Express'],
    ['6011111111111117', 'Discover'],
    ['30569309025904', 'Diners Club'],
    ['3530111333300000', 'JCB'],
    ['2204000000000000', 'Mir'],
    ['6763000000000004', 'Maestro'],
  ])('returns true for a valid %s number (%s)', (number) => {
    expect(isValidCardNumber(number)).toBe(true);
  });

  test.each([
    ['4111111111111112', 'Visa with corrupted last digit'],
    ['5555555555554441', 'MasterCard with corrupted last digit'],
    ['1234567890123456', 'random digits'],
  ])('returns false for an invalid number (%s)', (number) => {
    expect(isValidCardNumber(number)).toBe(false);
  });

  test('strips spaces and dashes before validating', () => {
    expect(isValidCardNumber('4111 1111 1111 1111')).toBe(true);
    expect(isValidCardNumber('4111-1111-1111-1111')).toBe(true);
  });

  test('returns false for an empty string', () => {
    expect(isValidCardNumber('')).toBe(false);
  });

  test('returns false for a number shorter than 12 digits', () => {
    expect(isValidCardNumber('411111111')).toBe(false);
  });

  test('returns false for a number longer than 19 digits', () => {
    expect(isValidCardNumber('41111111111111111111')).toBe(false);
  });

  test('returns false for non-numeric input', () => {
    expect(isValidCardNumber('not a card number')).toBe(false);
  });
});
